# Increase CR Version with each major release.
PRODUCT_VERSION_MAJOR = 10
PRODUCT_VERSION_MINOR = 11
ifeq ($(WITH_GMS), true)
  PRODUCT_FLAVOR := -microG
endif

# Internal version
LINEAGE_VERSION := v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)$(PRODUCT_FLAVOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)

# Display version
LINEAGE_DISPLAY_VERSION := v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)$(PRODUCT_FLAVOR)-$(LINEAGE_BUILD)
